/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "core_cm4.h"
#include <stm32l4xx.h>

int main(void)
{
	SET_BIT(RCC -> AHB2ENR, RCC_AHB2ENR_GPIOBEN);

    GPIOB->MODER &= ~GPIO_MODER_MODE3;
    GPIOB->MODER |= GPIO_MODER_MODE3_0;

	//SysTick_Config(SystemCoreClock/2);
    /* Loop forever */
	for(;;);
}

void SysTick_Handler(void)
{
	GPIOB->ODR ^= GPIO_ODR_OD3;
}
